refactor: Modify the .bin/serve

diff --git a/.bin/serve b/.bin/serve
--- a/.bin/serve
+++ b/.bin/serve
@@ -1,8 +1,33 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-usage_exit() {
+function usage_exit() {
   echo "Usage: $0 [-p port] [up|down]" 1>&2
   exit 1
+}
+
+function serve_up() {
+  port=$1
+  if [ -e "$cidfile" ]; then
+    echo "Already running" 1>&2
+    exit 4
+  else
+    docker run -d -v $(pwd):/usr/share/nginx/html:ro -p $port:80 nginx > $cidfile &&
+    echo -e "Start up successfully in localhost:$port"
+  fi
+}
+
+function serve_down() {
+  port=$1
+  if [ -r "$cidfile" ]; then
+    cid=$(head -n 1 $cidfile)
+    docker stop $cid > /dev/null && \
+    docker rm $cid > /dev/null && \
+    rm $cidfile && \
+    echo "Shut down successfully"
+  else
+    echo "Cannot read: $cidfile" 1>&2
+    exit 3
+  fi
 }
 
 cidfile=.serve
@@ -24,24 +49,9 @@ shift $((OPTIND - 1))
 if [ -z "$1" ]; then
   usage_exit
 elif [ "$1" = up ]; then
-  if [ -e "$cidfile" ]; then
-    echo "Already running" 1>&2
-    exit 4
-  else
-    docker run -d -v $(pwd):/usr/share/nginx/html:ro -p $port:80 nginx > $cidfile &&
-    echo -e "Start up successfully in localhost:$port"
-  fi
+  serve_up $port
 elif [ "$1" = down ]; then
-  if [ -r "$cidfile" ]; then
-    cid=$(head -n 1 $cidfile)
-    docker stop $cid > /dev/null && \
-    docker rm $cid > /dev/null && \
-    rm $cidfile && \
-    echo "Shut down successfully"
-  else
-    echo "Cannot read: $cidfile" 1>&2
-    exit 3
-  fi
+  serve_down $port
 else
   echo "Unknown command: $1" 1>&2
   exit 2
